/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/
class Solution {
    public char findTheDifference(String s, String t) {
        int[] count = new int[26];
        
        for (int iter = 0; iter < s.length(); iter++) {
            count[s.charAt(iter) - 'a']++;
            count[t.charAt(iter) - 'a']--;
        }
        //we know that t is longer than s exactly by 1 symbol
        count[t.charAt(t.length() - 1) - 'a']--;
        for (int iter = 0; iter < count.length; iter++) {
            if (count[iter] == -1) {
                return (char) (iter + 'a');
            }
        }
        return ' ';
    }
}
